apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo-05
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat
      - stage: prod
  template:
    metadata:
      name: kargo-demo-05-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo-05:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        # Kargo will update targetRevision to move new charts into each stage
        targetRevision: placeholder
        helm:
          parameters:
          # Kargo will update this value to move new images into each stage
          - name: image.tag
            value: placeholder
          - name: service.type
            value: ClusterIP
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-demo-05-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
  ignoreApplicationDifferences:
  - jqPathExpressions:
    - .spec.source.targetRevision
    - .spec.source.helm.parameters