apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/dhpup/kargo-helm.git
      # Watch this branch instead of main. This is the "trunk" for this example.
      branch: helm
  - image:
      repoURL: public.ecr.aws/nginx/nginx # Watch for new versions of this image
      semverConstraint: ^1.24.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/dhpup/kargo-helm.git
      writeBranch: stage/test # Write to stage-specific branch
      helm:
        images:
        - image: public.ecr.aws/nginx/nginx
          valuesFilePath: charts/kargo-demo/stages/test/values.yaml
          key: image.name # Update this key to reference the new image version
          value: ImageAndTag
    argoCDAppUpdates:
    - appName: kargo-demo-test
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/dhpup/kargo-helm.git
      writeBranch: stage/uat # Write to stage-specific branch
      helm:
        images:
        - image: public.ecr.aws/nginx/nginx
          valuesFilePath: charts/kargo-demo/stages/uat/values.yaml
          key: image.name # Update this key to reference the new image version
          value: ImageAndTag
    argoCDAppUpdates:
    - appName: kargo-demo-uat
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/dhpup/kargo-helm.git
      writeBranch: stage/prod # Write to stage-specific branch
      helm:
        images:
        - image: public.ecr.aws/nginx/nginx
          valuesFilePath: charts/kargo-demo/stages/prod/values.yaml
          key: image.name # Update this key to reference the new image version
          value: ImageAndTag
    argoCDAppUpdates:
    - appName: kargo-demo-prod
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never