apiVersion: v1
kind: Service
metadata:
  name: {{ include "kargo-h.fullname" . }}
  labels:
    {{- include "kargo-h.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    {{- include "kargo-h.selectorLabels" . | nindent 4 }}