apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kargo-h.fullname" . }}
  labels:
    {{- include "kargo-h.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kargo-h.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kargo-h.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: guestbook
        image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}